# -*- coding: utf-8 -*-
"""
test_render_views.py - render_views 模块测试

测试覆盖:
    - 空数据场景（无 items 时的渲染行为）
    - 少量数据场景（几条 items 的正常渲染）
    - 包含 attachment 的场景（验证 attachment 不影响渲染）
    - 默认路径、文件命名、覆盖策略验证
"""

import json
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Generator
from unittest.mock import MagicMock, patch

import pytest


# ---------- 常量 ----------

DEFAULT_OUT_DIR = "./.agentx/logbook/views"
EXPECTED_FILES = {"manifest.csv", "index.md", ".views_meta.json"}
AUTO_GENERATED_MARKER = "AUTO-GENERATED by render_views.py - DO NOT EDIT"


# ---------- 辅助函数 ----------

def create_mock_items(count: int, with_events: bool = True) -> list:
    """创建模拟的 items 列表"""
    items = []
    base_time = datetime(2025, 1, 1, 12, 0, 0)
    
    for i in range(count):
        item = {
            "item_id": i + 1,
            "item_type": "task" if i % 2 == 0 else "bug",
            "title": f"Test Item {i + 1}",
            "status": "open" if i % 3 == 0 else "in_progress",
            "owner_user_id": f"user_{i % 3}",
            "created_at": base_time,
            "updated_at": base_time,
        }
        
        if with_events:
            item["latest_event_id"] = 100 + i
            item["latest_event_type"] = "status_change" if i % 2 == 0 else "comment"
            item["latest_event_ts"] = base_time
        else:
            item["latest_event_id"] = None
            item["latest_event_type"] = None
            item["latest_event_ts"] = None
        
        items.append(item)
    
    return items


# ---------- 测试：默认配置与常量 ----------

class TestRenderViewsDefaults:
    """测试 render_views 默认配置"""
    
    def test_default_out_dir_constant(self):
        """验证默认输出目录常量"""
        from render_views import DEFAULT_OUT_DIR as ACTUAL_DEFAULT
        assert ACTUAL_DEFAULT == "./.agentx/logbook/views"
    
    def test_default_limit_constant(self):
        """验证默认 limit 常量"""
        from render_views import DEFAULT_LIMIT
        assert DEFAULT_LIMIT == 50
    
    def test_auto_generated_marker_constant(self):
        """验证自动生成标记常量"""
        from render_views import AUTO_GENERATED_MARKER as ACTUAL_MARKER
        assert "AUTO-GENERATED" in ACTUAL_MARKER
        assert "DO NOT EDIT" in ACTUAL_MARKER


# ---------- 测试：空数据场景 ----------

class TestRenderViewsEmptyData:
    """测试空数据场景"""
    
    def test_empty_items_generates_valid_files(self):
        """空数据时应生成有效的空文件结构"""
        from render_views import generate_manifest_csv, generate_index_md
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            out_path = Path(tmp_dir)
            items = []  # 空列表
            
            # 生成 manifest.csv
            manifest_path = out_path / "manifest.csv"
            manifest_info = generate_manifest_csv(items, manifest_path)
            
            assert manifest_path.exists()
            assert manifest_info["size"] > 0  # 至少有 header
            
            # 检查 manifest.csv 内容
            content = manifest_path.read_text(encoding="utf-8")
            assert AUTO_GENERATED_MARKER in content
            assert "item_id" in content  # header 存在
            lines = [l for l in content.split("\n") if l.strip() and not l.startswith("#")]
            assert len(lines) == 1  # 只有 header，无数据行
    
    def test_empty_items_index_shows_zero_count(self):
        """空数据时 index.md 应显示 0 条记录"""
        from render_views import generate_index_md
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            out_path = Path(tmp_dir)
            items = []
            
            index_path = out_path / "index.md"
            index_info = generate_index_md(items, index_path, limit=50)
            
            assert index_path.exists()
            content = index_path.read_text(encoding="utf-8")
            
            assert AUTO_GENERATED_MARKER in content
            assert "Total items: 0" in content
            assert "Showing: 0" in content
    
    @patch("render_views.db.get_items_with_latest_event")
    def test_render_views_empty_database(self, mock_get_items):
        """数据库为空时的完整渲染流程"""
        from render_views import render_views
        
        mock_get_items.return_value = []
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            result = render_views(
                out_dir=tmp_dir,
                limit=50,
                quiet=True,
            )
            
            assert result["items_count"] == 0
            assert "manifest" in result["files"]
            assert "index" in result["files"]
            
            # 验证文件存在
            out_path = Path(tmp_dir)
            assert (out_path / "manifest.csv").exists()
            assert (out_path / "index.md").exists()
            assert (out_path / ".views_meta.json").exists()


# ---------- 测试：少量数据场景 ----------

class TestRenderViewsSmallData:
    """测试少量数据场景"""
    
    def test_few_items_manifest(self):
        """少量数据生成的 manifest.csv 验证"""
        from render_views import generate_manifest_csv
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            items = create_mock_items(3)
            manifest_path = Path(tmp_dir) / "manifest.csv"
            
            manifest_info = generate_manifest_csv(items, manifest_path)
            
            assert manifest_path.exists()
            content = manifest_path.read_text(encoding="utf-8")
            
            # 检查 header + 3 行数据
            lines = [l for l in content.split("\n") if l.strip() and not l.startswith("#")]
            assert len(lines) == 4  # 1 header + 3 data
            
            # 检查数据内容
            assert "Test Item 1" in content
            assert "Test Item 2" in content
            assert "Test Item 3" in content
    
    def test_few_items_index_table(self):
        """少量数据生成的 index.md 表格验证"""
        from render_views import generate_index_md
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            items = create_mock_items(3, with_events=True)
            index_path = Path(tmp_dir) / "index.md"
            
            generate_index_md(items, index_path, limit=50)
            
            content = index_path.read_text(encoding="utf-8")
            
            assert "Total items: 3" in content
            assert "Showing: 3" in content
            
            # 检查表格行
            assert "| 1 |" in content
            assert "| 2 |" in content
            assert "| 3 |" in content
    
    def test_limit_truncates_index(self):
        """limit 参数应截断 index.md 中显示的条目数"""
        from render_views import generate_index_md
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            items = create_mock_items(10)
            index_path = Path(tmp_dir) / "index.md"
            
            generate_index_md(items, index_path, limit=5)
            
            content = index_path.read_text(encoding="utf-8")
            
            assert "Total items: 10" in content
            assert "Showing: 5" in content
            
            # 只显示前 5 条
            assert "| 1 |" in content
            assert "| 5 |" in content
            assert "| 6 |" not in content
    
    @patch("render_views.db.get_items_with_latest_event")
    def test_render_views_small_dataset(self, mock_get_items):
        """少量数据的完整渲染流程"""
        from render_views import render_views
        
        mock_get_items.return_value = create_mock_items(5)
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            result = render_views(
                out_dir=tmp_dir,
                limit=50,
                quiet=True,
            )
            
            assert result["items_count"] == 5
            assert result["files"]["manifest"]["size"] > 0
            assert result["files"]["index"]["size"] > 0
            
            # 验证 meta 文件
            meta_path = Path(tmp_dir) / ".views_meta.json"
            assert meta_path.exists()
            
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            assert meta["items_count"] == 5
            assert meta["generator"] == "render_views.py"


# ---------- 测试：包含 attachment 的场景 ----------

class TestRenderViewsWithAttachments:
    """测试包含 attachment 的场景"""
    
    @patch("render_views.db.get_items_with_latest_event")
    def test_items_with_attachment_events(self, mock_get_items):
        """包含 attachment 类型事件的 items 应正常渲染"""
        from render_views import render_views
        
        # 创建包含 attachment 事件的 items
        items = create_mock_items(3)
        items[0]["latest_event_type"] = "attachment_added"
        items[1]["latest_event_type"] = "file_uploaded"
        
        mock_get_items.return_value = items
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            result = render_views(
                out_dir=tmp_dir,
                limit=50,
                quiet=True,
            )
            
            assert result["items_count"] == 3
            
            # 验证 index.md 中包含 attachment 事件类型
            index_path = Path(tmp_dir) / "index.md"
            content = index_path.read_text(encoding="utf-8")
            
            assert "attachment_added" in content
            assert "file_uploaded" in content
    
    @patch("render_views.db.get_items_with_latest_event")
    @patch("render_views.db.add_event")
    @patch("render_views.db.attach")
    @patch("render_views.get_effective_artifacts_root")
    def test_log_event_creates_attachment_records(
        self,
        mock_artifacts_root,
        mock_attach,
        mock_add_event,
        mock_get_items,
    ):
        """使用 --log-event 时应创建 attachment 记录"""
        from render_views import render_views
        
        mock_get_items.return_value = create_mock_items(2)
        mock_add_event.return_value = 999  # event_id
        mock_attach.return_value = 888  # attachment_id
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            mock_artifacts_root.return_value = tmp_dir
            
            result = render_views(
                out_dir=tmp_dir,
                limit=50,
                log_event=True,
                item_id_for_log=42,
                quiet=True,
            )
            
            assert result["event_id"] == 999
            assert result["manifest_attachment_id"] == 888
            assert result["index_attachment_id"] == 888
            
            # 验证 attach 被调用了两次（manifest + index）
            assert mock_attach.call_count == 2


# ---------- 测试：覆盖策略 ----------

class TestRenderViewsOverwritePolicy:
    """测试文件覆盖策略"""
    
    @patch("render_views.db.get_items_with_latest_event")
    def test_overwrites_existing_files(self, mock_get_items):
        """应完全覆盖已存在的文件"""
        from render_views import render_views
        
        mock_get_items.return_value = create_mock_items(2)
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            # 创建旧文件
            manifest_path = Path(tmp_dir) / "manifest.csv"
            index_path = Path(tmp_dir) / "index.md"
            
            manifest_path.write_text("OLD CONTENT - SHOULD BE OVERWRITTEN")
            index_path.write_text("OLD INDEX - SHOULD BE OVERWRITTEN")
            
            old_manifest_content = manifest_path.read_text()
            
            # 执行渲染
            render_views(out_dir=tmp_dir, limit=50, quiet=True)
            
            # 验证文件被覆盖
            new_manifest_content = manifest_path.read_text(encoding="utf-8")
            new_index_content = index_path.read_text(encoding="utf-8")
            
            assert "OLD CONTENT" not in new_manifest_content
            assert "OLD INDEX" not in new_index_content
            assert AUTO_GENERATED_MARKER in new_manifest_content
            assert AUTO_GENERATED_MARKER in new_index_content
    
    @patch("render_views.db.get_items_with_latest_event")
    def test_creates_directory_if_not_exists(self, mock_get_items):
        """目标目录不存在时应自动创建"""
        from render_views import render_views
        
        mock_get_items.return_value = create_mock_items(1)
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            nested_out_dir = Path(tmp_dir) / "nested" / "deep" / "views"
            
            assert not nested_out_dir.exists()
            
            render_views(out_dir=str(nested_out_dir), limit=50, quiet=True)
            
            assert nested_out_dir.exists()
            assert (nested_out_dir / "manifest.csv").exists()
            assert (nested_out_dir / "index.md").exists()


# ---------- 测试：元数据文件 ----------

class TestRenderViewsMetadata:
    """测试元数据文件生成"""
    
    @patch("render_views.db.get_items_with_latest_event")
    def test_meta_file_structure(self, mock_get_items):
        """验证 .views_meta.json 结构"""
        from render_views import render_views
        
        mock_get_items.return_value = create_mock_items(3)
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            render_views(out_dir=tmp_dir, limit=50, quiet=True)
            
            meta_path = Path(tmp_dir) / ".views_meta.json"
            assert meta_path.exists()
            
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            
            # 验证必需字段
            assert meta["generator"] == "render_views.py"
            assert meta["marker"] == AUTO_GENERATED_MARKER
            assert "rendered_at" in meta
            assert meta["items_count"] == 3
            
            # 验证文件信息
            assert "manifest.csv" in meta["files"]
            assert "index.md" in meta["files"]
            
            for filename, info in meta["files"].items():
                assert "sha256" in info
                assert "size" in info
                assert len(info["sha256"]) == 64  # SHA256 长度
    
    @patch("render_views.db.get_items_with_latest_event")
    def test_meta_sha256_matches_actual_files(self, mock_get_items):
        """验证元数据中的 SHA256 与实际文件一致"""
        from render_views import render_views
        from engram.logbook.hashing import get_file_info
        
        mock_get_items.return_value = create_mock_items(2)
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            render_views(out_dir=tmp_dir, limit=50, quiet=True)
            
            meta_path = Path(tmp_dir) / ".views_meta.json"
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            
            # 验证 manifest.csv
            manifest_info = get_file_info(str(Path(tmp_dir) / "manifest.csv"))
            assert meta["files"]["manifest.csv"]["sha256"] == manifest_info["hash"]
            assert meta["files"]["manifest.csv"]["size"] == manifest_info["size"]
            
            # 验证 index.md
            index_info = get_file_info(str(Path(tmp_dir) / "index.md"))
            assert meta["files"]["index.md"]["sha256"] == index_info["hash"]
            assert meta["files"]["index.md"]["size"] == index_info["size"]


# ---------- 测试：边界情况 ----------

class TestRenderViewsEdgeCases:
    """测试边界情况"""
    
    def test_title_with_pipe_character(self):
        """标题包含 | 字符时应正确转义"""
        from render_views import generate_index_md
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            items = [{
                "item_id": 1,
                "item_type": "task",
                "title": "Test | with | pipes",
                "status": "open",
                "owner_user_id": "user_1",
                "created_at": datetime.now(),
                "updated_at": datetime.now(),
                "latest_event_id": 100,
                "latest_event_type": "create",
                "latest_event_ts": datetime.now(),
            }]
            
            index_path = Path(tmp_dir) / "index.md"
            generate_index_md(items, index_path, limit=50)
            
            content = index_path.read_text(encoding="utf-8")
            
            # | 应被转义为 \|
            assert "Test \\| with \\| pipes" in content
    
    def test_items_without_latest_event(self):
        """没有事件的 items 应显示 - 占位符"""
        from render_views import generate_index_md
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            items = create_mock_items(2, with_events=False)
            
            index_path = Path(tmp_dir) / "index.md"
            generate_index_md(items, index_path, limit=50)
            
            content = index_path.read_text(encoding="utf-8")
            
            # 无事件时显示 -
            # 表格行格式：| ID | Type | Title | Status | Latest Event | Time |
            lines = content.split("\n")
            data_lines = [l for l in lines if l.startswith("| ") and "ID" not in l and "---" not in l]
            
            for line in data_lines:
                # 最后两列应该是 - | - |
                assert "| - | - |" in line


# ---------- 集成测试（需要数据库） ----------

@pytest.mark.usefixtures("db_conn")
class TestRenderViewsIntegration:
    """集成测试（需要数据库连接）"""
    
    def test_render_with_real_database(self, db_conn, migrated_db):
        """使用真实数据库的集成测试"""
        from render_views import render_views
        from engram.logbook import db as db_module
        
        # 插入测试数据
        with db_conn.cursor() as cur:
            cur.execute("""
                INSERT INTO logbook.items (item_type, title, status)
                VALUES ('task', 'Integration Test Item', 'open')
                RETURNING item_id
            """)
            item_id = cur.fetchone()[0]
            
            cur.execute("""
                INSERT INTO logbook.events (item_id, event_type, source)
                VALUES (%s, 'create', 'test')
            """, (item_id,))
            
            db_conn.commit()
        
        # Mock get_connection 使用测试连接
        with tempfile.TemporaryDirectory() as tmp_dir:
            # 直接使用 DSN 调用
            with patch.object(db_module, 'get_connection', return_value=db_conn):
                with patch.object(db_module, '_conn', db_conn):
                    result = render_views(
                        out_dir=tmp_dir,
                        limit=10,
                        quiet=True,
                    )
            
            assert result["items_count"] >= 1
            
            # 验证文件
            manifest_path = Path(tmp_dir) / "manifest.csv"
            content = manifest_path.read_text(encoding="utf-8")
            assert "Integration Test Item" in content
