#!/usr/bin/env python3
"""
Write local env file (.env.local) for native runs.

Goals:
- Reduce missed manual exports after `make setup-db` interactive password input.
- Keep secrets out of version control (.env.local is gitignored).
- Make it easier to start OpenMemory in another terminal by emitting common OM_* vars.
- Preserve user-added keys (e.g. OM_API_KEY) across rewrites.

Inputs (via environment variables):
- ENV_LOCAL_FILE (default: .env.local)
- PROJECT_KEY, OPENMEMORY_BASE_URL, GATEWAY_PORT
- POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB
- ADMIN_DSN (fallback DSN when LOGBOOK_SVC_PASSWORD not present)
- LOGBOOK_MIGRATOR_PASSWORD, LOGBOOK_SVC_PASSWORD,
  OPENMEMORY_MIGRATOR_PASSWORD, OPENMEMORY_SVC_PASSWORD
- OM_PG_SCHEMA (optional)
- OM_API_KEY, OM_PORT, OM_VEC_DIM, OM_TIER (optional; preserved if already in file)
"""

from __future__ import annotations

import os
import re
import time
from pathlib import Path


def _dotenv_quote(value: str) -> str:
    """Quote a value for dotenv-style KEY="value" lines."""
    v = value.replace("\\", "\\\\").replace('"', '\\"')
    v = v.replace("\r", "\\r").replace("\n", "\\n")
    return f'"{v}"'


def _get(name: str) -> str:
    return os.environ.get(name, "").strip()


_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _parse_existing_kv_lines(existing: str) -> dict[str, str]:
    """
    Parse existing dotenv-like content into {KEY: raw_line}.

    - Keeps the full raw line to preserve original quoting/format.
    - Ignores comments/blank lines.
    - Only accepts valid KEY names and KEY=VALUE forms.
    """
    kv: dict[str, str] = {}
    for raw in existing.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _ = line.split("=", 1)
        key = key.strip()
        if not _KEY_RE.match(key):
            continue
        kv.setdefault(key, raw)
    return kv


def _extract_preserved_lines(existing: str, reserved_keys: set[str]) -> list[str]:
    """
    Preserve user-added KEY=VALUE lines that are not part of our generated set.

    Notes:
    - We intentionally do NOT preserve comments/header to keep the file tidy.
    - We only preserve simple KEY=VALUE lines with valid KEY names.
    """
    preserved: list[str] = []
    for raw in existing.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _ = line.split("=", 1)
        key = key.strip()
        if not _KEY_RE.match(key):
            continue
        if key in reserved_keys:
            continue
        preserved.append(raw)
    return preserved


def main() -> int:
    path = Path(os.environ.get("ENV_LOCAL_FILE", ".env.local"))

    existing_content = ""
    if path.exists():
        try:
            existing_content = path.read_text(encoding="utf-8")
        except Exception:
            existing_content = ""
    existing_kv_lines = _parse_existing_kv_lines(existing_content) if existing_content else {}

    backup: Path | None = None
    if path.exists():
        ts = time.strftime("%Y%m%d_%H%M%S")
        backup = path.with_suffix(path.suffix + f".bak.{ts}")
        path.replace(backup)

    base_keys = [
        "PROJECT_KEY",
        "OPENMEMORY_BASE_URL",
        "GATEWAY_PORT",
        "POSTGRES_HOST",
        "POSTGRES_PORT",
        "POSTGRES_DB",
        "OM_PG_SCHEMA",
        "LOGBOOK_MIGRATOR_PASSWORD",
        "LOGBOOK_SVC_PASSWORD",
        "OPENMEMORY_MIGRATOR_PASSWORD",
        "OPENMEMORY_SVC_PASSWORD",
    ]

    # User-managed / optional keys (we will write them if present, and preserve them otherwise)
    optional_keys = [
        "OM_API_KEY",
        "OM_PORT",
        "OM_VEC_DIM",
        "OM_TIER",
        "OM_METADATA_BACKEND",
        "OM_PG_HOST",
        "OM_PG_PORT",
        "OM_PG_DB",
        "OM_PG_USER",
        "OM_PG_PASSWORD",
    ]

    reserved_keys = set(base_keys) | set(optional_keys) | {"POSTGRES_DSN"}
    preserved_lines = _extract_preserved_lines(existing_content, reserved_keys)

    lines: list[str] = [
        "# Auto-generated by `make setup-db` (local only; ignored by git)",
        f"# Updated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
    ]

    for k in base_keys:
        val = _get(k)
        if not val:
            continue
        lines.append(f"{k}={_dotenv_quote(val)}")

    host = _get("POSTGRES_HOST") or "localhost"
    port = _get("POSTGRES_PORT") or "5432"
    db = _get("POSTGRES_DB") or "engram"
    lb_pw = _get("LOGBOOK_SVC_PASSWORD")
    admin_dsn = _get("ADMIN_DSN")

    if lb_pw:
        dsn = f"postgresql://logbook_svc:{lb_pw}@{host}:{port}/{db}"
    else:
        dsn = admin_dsn or f"postgresql://{host}:{port}/{db}"

    lines.append(f"POSTGRES_DSN={_dotenv_quote(dsn)}")

    # Emit common OpenMemory env vars so "source .env.local && opm serve" works.
    # If users have already set these, we prefer explicit OM_* values.
    om_schema = _get("OM_PG_SCHEMA") or "openmemory"
    om_pg_host = _get("OM_PG_HOST") or host
    om_pg_port = _get("OM_PG_PORT") or port
    om_pg_db = _get("OM_PG_DB") or db
    om_pg_user = _get("OM_PG_USER") or "openmemory_migrator_login"
    if om_pg_user == "openmemory_migrator_login":
        default_om_pw = _get("OPENMEMORY_MIGRATOR_PASSWORD") or _get("OPENMEMORY_SVC_PASSWORD")
    else:
        default_om_pw = _get("OPENMEMORY_SVC_PASSWORD") or _get("OPENMEMORY_MIGRATOR_PASSWORD")
    om_pg_password = _get("OM_PG_PASSWORD") or default_om_pw

    def _existing_line_for(key: str) -> str | None:
        return existing_kv_lines.get(key)

    # Allow optional keys to persist even when env isn't set (e.g. OM_API_KEY).
    def _append_optional(key: str) -> None:
        val = _get(key)
        if val:
            lines.append(f"{key}={_dotenv_quote(val)}")
            return
        raw = _existing_line_for(key)
        if raw is not None:
            lines.append(raw)

    om_backend = _get("OM_METADATA_BACKEND") or (
        _existing_line_for("OM_METADATA_BACKEND").split("=", 1)[1].strip()
        if _existing_line_for("OM_METADATA_BACKEND") is not None
        else "postgres"
    )
    om_port = _get("OM_PORT") or (
        _existing_line_for("OM_PORT").split("=", 1)[1].strip()
        if _existing_line_for("OM_PORT") is not None
        else "8080"
    )

    lines.append(f"OM_METADATA_BACKEND={_dotenv_quote(om_backend)}")
    lines.append(f"OM_PG_HOST={_dotenv_quote(om_pg_host)}")
    lines.append(f"OM_PG_PORT={_dotenv_quote(om_pg_port)}")
    lines.append(f"OM_PG_DB={_dotenv_quote(om_pg_db)}")
    lines.append(f"OM_PG_USER={_dotenv_quote(om_pg_user)}")
    if om_pg_password:
        lines.append(f"OM_PG_PASSWORD={_dotenv_quote(om_pg_password)}")
    lines.append(f"OM_PG_SCHEMA={_dotenv_quote(om_schema)}")
    lines.append(f"OM_PORT={_dotenv_quote(om_port)}")

    _append_optional("OM_API_KEY")
    _append_optional("OM_VEC_DIM")
    _append_optional("OM_TIER")

    if preserved_lines:
        lines.append("")
        lines.append("# Preserved user-added keys from previous .env.local")
        lines.extend(preserved_lines)

    content = "\n".join(lines) + "\n"
    tmp = path.with_suffix(path.suffix + ".tmp")

    old_umask = os.umask(0o177)
    try:
        tmp.write_text(content, encoding="utf-8")
    finally:
        os.umask(old_umask)

    tmp.replace(path)
    try:
        os.chmod(path, 0o600)
    except Exception:
        # Best-effort only.
        pass

    print(f"[OK] wrote {path}")
    if backup is not None:
        print(f"[INFO] previous file backed up: {backup}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

