"""
engram_step1.views - 生成 logbook 的视图文件

功能:
    - 查询 logbook.items（联表取最近事件时间/类型）
    - 生成 manifest.csv
    - 生成 index.md（最近 N 条 item 的导航）
    - 默认输出到 ./.agentx/logbook/views/，支持 --out-dir
    - 渲染完成后可选写入 logbook.events 记录（event_type=render_views）

输出格式:
    - 成功: {ok: true, ...}
    - 失败: {ok: false, code, message, detail}
"""

import csv
import json as _json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from engram_step1 import db
from engram_step1.config import get_effective_artifacts_root
from engram_step1.hashing import get_file_info
from engram_step1.io import log_info
from engram_step1.uri import normalize_uri

# 默认输出目录
DEFAULT_OUT_DIR = "./.agentx/logbook/views"

# 默认最近条目数量
DEFAULT_LIMIT = 50

# 自动生成文件标识
AUTO_GENERATED_MARKER = "AUTO-GENERATED by render_views.py - DO NOT EDIT"
AUTO_GENERATED_MARKER_CN = "此文件由 render_views.py 自动生成，请勿手动修改"


def ensure_directory(path: Path) -> None:
    """确保目录存在"""
    path.mkdir(parents=True, exist_ok=True)


def format_datetime(dt: Optional[datetime]) -> str:
    """格式化日期时间"""
    if dt is None:
        return ""
    return dt.isoformat()


def generate_manifest_csv(items: List[Dict[str, Any]], out_path: Path) -> Dict[str, Any]:
    """
    生成 manifest.csv

    Args:
        items: item 列表
        out_path: 输出路径

    Returns:
        文件信息（路径、大小、哈希）
    """
    ensure_directory(out_path.parent)

    fieldnames = [
        "item_id",
        "item_type",
        "title",
        "status",
        "owner_user_id",
        "created_at",
        "updated_at",
        "latest_event_id",
        "latest_event_type",
        "latest_event_ts",
    ]

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        # 写入自动生成警告注释（CSV 标准允许 # 开头的注释行）
        f.write(f"# {AUTO_GENERATED_MARKER}\n")
        f.write(f"# {AUTO_GENERATED_MARKER_CN}\n")
        f.write(f"# Generated at: {datetime.utcnow().isoformat()}Z\n")
        
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for item in items:
            row = {
                "item_id": item["item_id"],
                "item_type": item["item_type"],
                "title": item["title"],
                "status": item["status"],
                "owner_user_id": item.get("owner_user_id") or "",
                "created_at": format_datetime(item.get("created_at")),
                "updated_at": format_datetime(item.get("updated_at")),
                "latest_event_id": item.get("latest_event_id") or "",
                "latest_event_type": item.get("latest_event_type") or "",
                "latest_event_ts": format_datetime(item.get("latest_event_ts")),
            }
            writer.writerow(row)

    return get_file_info(str(out_path))


def generate_index_md(items: List[Dict[str, Any]], out_path: Path, limit: int = DEFAULT_LIMIT) -> Dict[str, Any]:
    """
    生成 index.md（最近 N 条 item 的导航）

    Args:
        items: item 列表
        out_path: 输出路径
        limit: 显示的最大条目数

    Returns:
        文件信息（路径、大小、哈希）
    """
    ensure_directory(out_path.parent)

    # 截取最近 N 条
    recent_items = items[:limit]

    lines = [
        f"<!-- {AUTO_GENERATED_MARKER} -->",
        f"<!-- {AUTO_GENERATED_MARKER_CN} -->",
        "",
        "# Logbook Items Index",
        "",
        f"> Generated at: {datetime.utcnow().isoformat()}Z",
        f"> Total items: {len(items)}, Showing: {len(recent_items)}",
        "",
        "> **⚠️ 注意**: 此文件由工具自动生成，请勿手动编辑。如需更新，请运行 `logbook_cli.py render_views`。",
        "",
        "## Recent Items",
        "",
        "| ID | Type | Title | Status | Latest Event | Time |",
        "|---:|:-----|:------|:-------|:-------------|:-----|",
    ]

    for item in recent_items:
        item_id = item["item_id"]
        item_type = item["item_type"]
        title = item["title"].replace("|", "\\|")  # 转义表格分隔符
        status = item["status"]
        latest_event_type = item.get("latest_event_type") or "-"
        latest_event_ts = item.get("latest_event_ts")

        if latest_event_ts:
            time_str = latest_event_ts.strftime("%Y-%m-%d %H:%M") if isinstance(latest_event_ts, datetime) else str(latest_event_ts)[:16]
        else:
            time_str = "-"

        lines.append(f"| {item_id} | {item_type} | {title} | {status} | {latest_event_type} | {time_str} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*See `manifest.csv` for complete data.*")
    lines.append("")

    content = "\n".join(lines)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    return get_file_info(str(out_path))


def render_views(
    out_dir: str = DEFAULT_OUT_DIR,
    limit: int = DEFAULT_LIMIT,
    item_type: Optional[str] = None,
    status: Optional[str] = None,
    log_event: bool = False,
    item_id_for_log: Optional[int] = None,
    config=None,
    quiet: bool = False,
) -> Dict[str, Any]:
    """
    渲染视图文件

    Args:
        out_dir: 输出目录
        limit: 最近条目数量上限
        item_type: 按 item_type 筛选
        status: 按状态筛选
        log_event: 是否写入 render_views 事件记录
        item_id_for_log: 用于记录事件的 item_id（log_event=True 时需要）
        config: 配置实例
        quiet: 静默模式

    Returns:
        渲染结果信息
    """
    out_path = Path(out_dir)

    log_info(f"输出目录: {out_path}", quiet=quiet)

    # 查询 items（联表取最近事件）
    items = db.get_items_with_latest_event(
        limit=limit * 2,  # 多查一些以便筛选
        item_type=item_type,
        status=status,
        config=config,
    )

    log_info(f"查询到 {len(items)} 条记录", quiet=quiet)

    # 生成文件
    manifest_path = out_path / "manifest.csv"
    index_path = out_path / "index.md"

    manifest_info = generate_manifest_csv(items, manifest_path)
    log_info(f"生成 manifest.csv: {manifest_info['size']} bytes", quiet=quiet)

    index_info = generate_index_md(items, index_path, limit=limit)
    log_info(f"生成 index.md: {index_info['size']} bytes", quiet=quiet)

    # 仅当需要写入 DB 附件记录时，才将渲染产物复制到 artifacts_root 并生成 artifact key
    manifest_artifact_key: Optional[str] = None
    index_artifact_key: Optional[str] = None

    rendered_at = datetime.utcnow().isoformat() + "Z"
    
    result = {
        "out_dir": str(out_path.resolve()),
        "items_count": len(items),
        "files": {
            "manifest": {
                "path": manifest_info["path"],
                "size": manifest_info["size"],
                "sha256": manifest_info["hash"],
            },
            "index": {
                "path": index_info["path"],
                "size": index_info["size"],
                "sha256": index_info["hash"],
            },
        },
        "rendered_at": rendered_at,
    }
    
    # 生成元数据文件（用于 validate 验证）
    meta_path = out_path / ".views_meta.json"
    meta_data = {
        "generator": "render_views.py",
        "marker": AUTO_GENERATED_MARKER,
        "rendered_at": rendered_at,
        "items_count": len(items),
        "files": {
            "manifest.csv": {
                "sha256": manifest_info["hash"],
                "size": manifest_info["size"],
            },
            "index.md": {
                "sha256": index_info["hash"],
                "size": index_info["size"],
            },
        },
    }
    
    with open(meta_path, "w", encoding="utf-8") as f:
        _json.dump(meta_data, f, indent=2, ensure_ascii=False)
    
    result["meta_path"] = str(meta_path.resolve())
    log_info(f"生成元数据: {meta_path}", quiet=quiet)

    # 可选：写入 render_views 事件记录（并把附件 URI 规范化为 artifact key）
    if log_event and item_id_for_log:
        artifacts_root = Path(get_effective_artifacts_root())
        artifacts_views_dir = artifacts_root / "logbook" / "views"
        ensure_directory(artifacts_views_dir)

        manifest_artifact_key = normalize_uri("logbook/views/manifest.csv")
        index_artifact_key = normalize_uri("logbook/views/index.md")

        manifest_artifacts_path = artifacts_root / manifest_artifact_key
        index_artifacts_path = artifacts_root / index_artifact_key

        try:
            if manifest_path.resolve() != manifest_artifacts_path.resolve():
                shutil.copy2(manifest_path, manifest_artifacts_path)
            if index_path.resolve() != index_artifacts_path.resolve():
                shutil.copy2(index_path, index_artifacts_path)
        except Exception as e:
            raise RuntimeError(f"将视图文件复制到 artifacts 目录失败: {e}")

        manifest_artifacts_info = get_file_info(str(manifest_artifacts_path))
        index_artifacts_info = get_file_info(str(index_artifacts_path))

        result["files"]["manifest"]["artifact_key"] = manifest_artifact_key
        result["files"]["index"]["artifact_key"] = index_artifact_key

        event_id = db.add_event(
            item_id=item_id_for_log,
            event_type="render_views",
            payload_json={
                "out_dir": str(out_path.resolve()),
                "items_count": len(items),
                "files": list(result["files"].keys()),
            },
            source="render_views",
            config=config,
        )
        result["event_id"] = event_id
        log_info(f"记录事件: event_id={event_id}", quiet=quiet)

        # 添加附件记录（manifest.csv）
        manifest_attachment_id = db.attach(
            item_id=item_id_for_log,
            kind="report",
            uri=manifest_artifact_key,
            sha256=manifest_artifacts_info["hash"],
            size_bytes=manifest_artifacts_info["size"],
            meta_json={
                "type": "manifest",
                "format": "csv",
                "source_path": manifest_info["path"],
            },
            config=config,
        )
        result["manifest_attachment_id"] = manifest_attachment_id

        # 添加附件记录（index.md）
        index_attachment_id = db.attach(
            item_id=item_id_for_log,
            kind="spec",
            uri=index_artifact_key,
            sha256=index_artifacts_info["hash"],
            size_bytes=index_artifacts_info["size"],
            meta_json={
                "type": "index",
                "format": "markdown",
                "source_path": index_info["path"],
            },
            config=config,
        )
        result["index_attachment_id"] = index_attachment_id

    return result
