# Engram Gateway 独立部署 Docker Compose
# 仅包含 Gateway + Worker
#
# 前置要求:
#   - 外部 PostgreSQL 已启动（可通过 make up-step1 启动）
#   - 外部 OpenMemory 已启动（可通过 make up-openmemory 启动）
#
# 使用方法:
#   make up-gateway                            # 从根目录启动
#   docker compose -f compose/gateway.yml up -d
#
# 必需环境变量:
#   - POSTGRES_DSN: PostgreSQL 连接字符串
#       例: postgresql://postgres:postgres@host.docker.internal:5432/engram
#       例: postgresql://step1_svc:password@localhost:5432/engram
#   - OPENMEMORY_BASE_URL: OpenMemory 服务地址
#       例: http://host.docker.internal:8080
#       例: http://localhost:8080
#
# 可选环境变量:
#   - GATEWAY_PORT: Gateway 端口（默认 8787）
#   - PROJECT_KEY: 项目标识（默认 default）
#   - OPENMEMORY_API_KEY: OpenMemory API 密钥
#   - WORKER_POLL_INTERVAL: Worker 轮询间隔秒数（默认 5）
#   - WORKER_BATCH_SIZE: Worker 批处理大小（默认 50）
#   - WORKER_LEASE_TIMEOUT: Worker 租约超时秒数（默认 300）

version: "3.8"

services:
  # ============================================================================
  # Memory Gateway 服务
  # 桥接 Step1 Logbook 与 OpenMemory
  # ============================================================================
  gateway:
    build:
      # context 必须为项目根目录
      context: ..
      dockerfile: apps/step2_openmemory_gateway/gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT:-8787}:8787"
    environment:
      PROJECT_KEY: ${PROJECT_KEY:-default}
      # 必需：外部 PostgreSQL 连接
      POSTGRES_DSN: ${POSTGRES_DSN:?POSTGRES_DSN is required}
      # 必需：外部 OpenMemory 连接
      OPENMEMORY_BASE_URL: ${OPENMEMORY_BASE_URL:?OPENMEMORY_BASE_URL is required}
      OPENMEMORY_API_KEY: ${OPENMEMORY_API_KEY:-}
      GATEWAY_PORT: "8787"
      DEFAULT_TEAM_SPACE: ${DEFAULT_TEAM_SPACE:-}
      PRIVATE_SPACE_PREFIX: ${PRIVATE_SPACE_PREFIX:-private:}
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8787/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - gateway-net
    # 如果连接宿主机服务，需要额外网络配置
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # ============================================================================
  # Outbox Worker 服务
  # 从 Step1 Outbox 消费事件并推送到 OpenMemory
  # ============================================================================
  worker:
    build:
      # context 必须为项目根目录
      context: ..
      dockerfile: apps/step2_openmemory_gateway/gateway/Dockerfile
    command: ["python", "-m", "gateway.outbox_worker"]
    environment:
      PROJECT_KEY: ${PROJECT_KEY:-default}
      # 必需：外部 PostgreSQL 连接
      POSTGRES_DSN: ${POSTGRES_DSN:?POSTGRES_DSN is required}
      # 必需：外部 OpenMemory 连接
      OPENMEMORY_BASE_URL: ${OPENMEMORY_BASE_URL:?OPENMEMORY_BASE_URL is required}
      OPENMEMORY_API_KEY: ${OPENMEMORY_API_KEY:-}
      # Worker 配置
      WORKER_POLL_INTERVAL: ${WORKER_POLL_INTERVAL:-5}
      WORKER_BATCH_SIZE: ${WORKER_BATCH_SIZE:-50}
      WORKER_LEASE_TIMEOUT: ${WORKER_LEASE_TIMEOUT:-300}
    restart: unless-stopped
    networks:
      - gateway-net
    # 如果连接宿主机服务，需要额外网络配置
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  gateway-net:
    driver: bridge
