# Logbook-only 部署 Compose 配置
#
# 服务账号策略（SKIP 模式）：
#   - 不设置任何 *_PASSWORD 环境变量时自动进入 SKIP 模式
#   - SKIP 模式下跳过服务账号创建，使用 postgres 超级用户
#   - 若设置了任意一个密码变量，则要求 4 个密码变量全部设置
#
# 使用方式：
#   # logbook-only 模式（推荐，无需配置密码）
#   docker compose -f compose/logbook.yml up -d
#
#   # 或者设置全部 4 个密码（unified-stack 模式）
#   export LOGBOOK_MIGRATOR_PASSWORD=xxx
#   export LOGBOOK_SVC_PASSWORD=xxx
#   export OPENMEMORY_MIGRATOR_PASSWORD=xxx
#   export OPENMEMORY_SVC_PASSWORD=xxx
#   docker compose -f compose/logbook.yml up -d

version: "3.9"

services:
  postgres:
    image: ${POSTGRES_IMAGE:-pgvector/pgvector:pg16}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-engram}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-engram}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks: [logbook_net]

  logbook_migrate:
    build:
      context: ..
      dockerfile: docker/engram.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-engram}
      # 服务账号密码（可选）：
      # - 全部不设置 → logbook-only 模式（SKIP 服务账号创建）
      # - 全部设置 → unified-stack 模式（创建服务账号）
      # - 部分设置 → 配置错误，容器初始化失败
      LOGBOOK_MIGRATOR_PASSWORD: ${LOGBOOK_MIGRATOR_PASSWORD:-}
      LOGBOOK_SVC_PASSWORD: ${LOGBOOK_SVC_PASSWORD:-}
      OPENMEMORY_MIGRATOR_PASSWORD: ${OPENMEMORY_MIGRATOR_PASSWORD:-}
      OPENMEMORY_SVC_PASSWORD: ${OPENMEMORY_SVC_PASSWORD:-}
      OM_PG_SCHEMA: ${OM_PG_SCHEMA:-openmemory}
    command: >
      sh -c 'engram-migrate --dsn "$POSTGRES_DSN" --apply-roles --apply-openmemory-grants'
    networks: [logbook_net]

  # ===== SCM Sync 服务 (scm_sync profile) =====
  # 启用方式: docker compose -f compose/logbook.yml --profile scm_sync up -d
  # 注意: 需要配置 GitLab/SVN 凭证，敏感变量不提供默认值

  scm_scheduler:
    build:
      context: ..
      dockerfile: docker/engram.Dockerfile
    profiles: ["scm_sync"]
    depends_on:
      postgres:
        condition: service_healthy
      logbook_migrate:
        condition: service_completed_successfully
    environment:
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-engram}
      ENGRAM_SCM_SYNC_ENABLED: ${ENGRAM_SCM_SYNC_ENABLED:-true}
      # GitLab 凭证（敏感，无默认值）
      GITLAB_URL: ${GITLAB_URL:-}
      GITLAB_TOKEN: ${GITLAB_TOKEN:-}
      GITLAB_PRIVATE_TOKEN: ${GITLAB_PRIVATE_TOKEN:-}
      # SVN 凭证（敏感，无默认值）
      SVN_USERNAME: ${SVN_USERNAME:-}
      SVN_PASSWORD: ${SVN_PASSWORD:-}
      # Scheduler 配置
      SCM_SCHEDULER_GLOBAL_CONCURRENCY: ${SCM_SCHEDULER_GLOBAL_CONCURRENCY:-20}
      SCM_SCHEDULER_MAX_RUNNING: ${SCM_SCHEDULER_MAX_RUNNING:-10}
      SCM_SCHEDULER_SCAN_INTERVAL_SECONDS: ${SCM_SCHEDULER_SCAN_INTERVAL_SECONDS:-60}
    command: ["engram-scm-scheduler", "--loop"]
    restart: unless-stopped
    networks: [logbook_net]

  scm_worker:
    build:
      context: ..
      dockerfile: docker/engram.Dockerfile
    profiles: ["scm_sync"]
    depends_on:
      postgres:
        condition: service_healthy
      logbook_migrate:
        condition: service_completed_successfully
    environment:
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-engram}
      ENGRAM_SCM_SYNC_ENABLED: ${ENGRAM_SCM_SYNC_ENABLED:-true}
      # GitLab 凭证（敏感，无默认值）
      GITLAB_URL: ${GITLAB_URL:-}
      GITLAB_TOKEN: ${GITLAB_TOKEN:-}
      GITLAB_PRIVATE_TOKEN: ${GITLAB_PRIVATE_TOKEN:-}
      # SVN 凭证（敏感，无默认值）
      SVN_USERNAME: ${SVN_USERNAME:-}
      SVN_PASSWORD: ${SVN_PASSWORD:-}
      # Worker 配置
      SCM_WORKER_LEASE_SECONDS: ${SCM_WORKER_LEASE_SECONDS:-300}
      SCM_WORKER_POLL_INTERVAL: ${SCM_WORKER_POLL_INTERVAL:-10}
      SCM_WORKER_PARALLELISM: ${SCM_WORKER_PARALLELISM:-2}
    command: ["engram-scm-worker"]
    restart: unless-stopped
    # 支持多副本: docker compose -f compose/logbook.yml --profile scm_sync up -d --scale scm_worker=3
    networks: [logbook_net]

  scm_reaper:
    build:
      context: ..
      dockerfile: docker/engram.Dockerfile
    profiles: ["scm_sync"]
    depends_on:
      postgres:
        condition: service_healthy
      logbook_migrate:
        condition: service_completed_successfully
    environment:
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-engram}
      ENGRAM_SCM_SYNC_ENABLED: ${ENGRAM_SCM_SYNC_ENABLED:-true}
      # Reaper 配置
      SCM_REAPER_INTERVAL_SECONDS: ${SCM_REAPER_INTERVAL_SECONDS:-60}
      SCM_REAPER_JOB_GRACE_SECONDS: ${SCM_REAPER_JOB_GRACE_SECONDS:-60}
      SCM_REAPER_LOCK_GRACE_SECONDS: ${SCM_REAPER_LOCK_GRACE_SECONDS:-120}
    command: ["engram-scm-reaper", "--loop"]
    restart: unless-stopped
    networks: [logbook_net]

networks:
  logbook_net:

volumes:
  pgdata:
