# Logbook-only 部署 Compose 配置
#
# 服务账号策略（SKIP 模式）：
#   - 不设置任何 *_PASSWORD 环境变量时自动进入 SKIP 模式
#   - SKIP 模式下跳过服务账号创建，使用 postgres 超级用户
#   - 若设置了任意一个密码变量，则要求 4 个密码变量全部设置
#
# 使用方式：
#   # logbook-only 模式（推荐，无需配置密码）
#   docker compose -f compose/logbook.yml up -d
#
#   # 或者设置全部 4 个密码（unified-stack 模式）
#   export LOGBOOK_MIGRATOR_PASSWORD=xxx
#   export LOGBOOK_SVC_PASSWORD=xxx
#   export OPENMEMORY_MIGRATOR_PASSWORD=xxx
#   export OPENMEMORY_SVC_PASSWORD=xxx
#   docker compose -f compose/logbook.yml up -d

version: "3.9"

services:
  postgres:
    image: ${POSTGRES_IMAGE:-pgvector/pgvector:pg16}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-engram}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-engram}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks: [logbook_net]

  logbook_migrate:
    build:
      context: ..
      dockerfile: docker/engram.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-engram}
      # 服务账号密码（可选）：
      # - 全部不设置 → logbook-only 模式（SKIP 服务账号创建）
      # - 全部设置 → unified-stack 模式（创建服务账号）
      # - 部分设置 → 配置错误，容器初始化失败
      LOGBOOK_MIGRATOR_PASSWORD: ${LOGBOOK_MIGRATOR_PASSWORD:-}
      LOGBOOK_SVC_PASSWORD: ${LOGBOOK_SVC_PASSWORD:-}
      OPENMEMORY_MIGRATOR_PASSWORD: ${OPENMEMORY_MIGRATOR_PASSWORD:-}
      OPENMEMORY_SVC_PASSWORD: ${OPENMEMORY_SVC_PASSWORD:-}
      OM_PG_SCHEMA: ${OM_PG_SCHEMA:-openmemory}
    command: >
      sh -c 'engram-migrate --dsn "$POSTGRES_DSN" --apply-roles --apply-openmemory-grants'
    networks: [logbook_net]

networks:
  logbook_net:

volumes:
  pgdata:
