# Engram Step1 独立部署 Docker Compose
# 仅包含 PostgreSQL + Step1 迁移工具
#
# 使用方法:
#   make up-step1                            # 从根目录启动
#   docker compose -f compose/step1.yml up -d
#
# 环境变量:
#   - POSTGRES_PORT: PostgreSQL 端口（默认 5432）
#   - POSTGRES_USER: PostgreSQL 用户（默认 postgres）
#   - POSTGRES_PASSWORD: PostgreSQL 密码（默认 postgres）
#   - POSTGRES_DB: 数据库名（默认 engram）
#   - PROJECT_KEY: 项目标识（默认 default）
#   - STEP1_MIGRATOR_PASSWORD: Step1 迁移账号密码（可选，不设置则使用 postgres 用户）

version: "3.8"

x-postgres-env: &postgres-env
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-engram}

services:
  # ============================================================================
  # PostgreSQL 数据库
  # ============================================================================
  postgres:
    image: postgres:16
    environment:
      <<: *postgres-env
      # 可选：服务账号密码（供 init 脚本创建）
      STEP1_MIGRATOR_PASSWORD: ${STEP1_MIGRATOR_PASSWORD:-}
      STEP1_SVC_PASSWORD: ${STEP1_SVC_PASSWORD:-}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - step1_postgres_data:/var/lib/postgresql/data
      # Step1 SQL 初始化脚本（首次启动时执行）
      - ../apps/step1_logbook_postgres/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-engram}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - step1-net

  # ============================================================================
  # Step1 数据库迁移 (one-shot)
  # 启用方式: --profile migrate 或 COMPOSE_PROFILES=migrate
  # ============================================================================
  step1_migrate:
    image: python:3.12-slim
    profiles:
      - migrate
    working_dir: /app
    volumes:
      - ../apps/step1_logbook_postgres:/app:ro
    environment:
      # 配置 DSN 直接连接
      ENGRAM_STEP1_CONFIG: ""
      # 如配置了 STEP1_MIGRATOR_PASSWORD，使用迁移账号；否则使用 postgres
      STEP1_MIGRATOR_PASSWORD: ${STEP1_MIGRATOR_PASSWORD:-}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-engram}
    command: >
      bash -c "
        pip install --quiet psycopg[binary] tomli &&
        cd /app/scripts &&
        
        # 根据是否配置了 STEP1_MIGRATOR_PASSWORD 选择连接用户
        if [ -n \"$${STEP1_MIGRATOR_PASSWORD}\" ]; then
          DSN=\"postgresql://step1_migrator:$${STEP1_MIGRATOR_PASSWORD}@postgres:5432/$${POSTGRES_DB}\"
          echo '[step1_migrate] 使用 step1_migrator 账号'
        else
          DSN=\"postgresql://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@postgres:5432/$${POSTGRES_DB}\"
          echo '[step1_migrate] 使用 postgres 超级用户'
        fi
        
        python db_migrate.py --quiet --dsn \"\$${DSN}\"
      "
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - step1-net
    restart: "no"

networks:
  step1-net:
    driver: bridge

volumes:
  step1_postgres_data:
    driver: local
