<#
One-shot Windows DB setup (similar to `make setup-db`):
- Choose deployment mode (logbook-only / unified-stack)
- In unified-stack mode, prompt for 4 service account passwords (hidden input)
- Optionally write/update repo-root `.\.env.ps1` (PowerShell dot-source; gitignored)
- Run `scripts/windows/install_db.ps1` to create DB, enable pgvector, bootstrap roles, migrate & grants
#
Notes:
- Ensure Postgres bin is on PATH (`psql`, `createdb`)
- Activate venv first (`engram-bootstrap-roles`, `engram-migrate` should be on PATH)
- For Postgres admin password, prefer pgpass.conf (or set `$env:PGPASSWORD` for this session)
#>

[CmdletBinding()]
param(
  [string]$ConfigPath = "$(Split-Path -Parent $MyInvocation.MyCommand.Path)\config.ps1",
  [string]$EnvPath = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function _QuotePsSingle([string]$value) {
  # Single-quote escaping: ' -> ''
  return "'" + ($value -replace "'", "''") + "'"
}

function _ReadSecretPlain([string]$prompt) {
  $secure = Read-Host $prompt -AsSecureString
  if ($null -eq $secure) { return "" }
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

function _ReadChoice([string]$prompt, [string]$default) {
  $raw = Read-Host $prompt
  if ([string]::IsNullOrWhiteSpace($raw)) { return $default }
  return $raw.Trim()
}

function _EnsureConfig([string]$path) {
  if (Test-Path $path) { return }
  $example = Join-Path (Split-Path -Parent $path) "config.ps1.example"
  if (-not (Test-Path $example)) { throw "Missing config example: $example" }
  Copy-Item -Force $example $path
  Write-Host "[OK] Created $path (please edit paths/ports as needed)"
}

function _UpsertEnvFile([string]$path, [string[]]$autoLines) {
  $begin = "# >>> engram-env (auto)"
  $end = "# <<< engram-env (auto)"

  $autoBlock = @()
  $autoBlock += $begin
  $autoBlock += "# Auto-generated by scripts/windows/setup_db.ps1 (local only; do not commit)"
  $autoBlock += "# Updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
  $autoBlock += $autoLines
  $autoBlock += $end

  $existing = ""
  if (Test-Path $path) {
    $existing = Get-Content -LiteralPath $path -Raw -ErrorAction SilentlyContinue
  }

  if ($existing -and $existing.Contains($begin) -and $existing.Contains($end)) {
    $pre = $existing.Substring(0, $existing.IndexOf($begin))
    $post = $existing.Substring($existing.IndexOf($end) + $end.Length)
    $newContent = ($pre.TrimEnd() + "`r`n" + ($autoBlock -join "`r`n") + "`r`n" + $post.TrimStart()).TrimEnd() + "`r`n"
    Set-Content -LiteralPath $path -Value $newContent -Encoding UTF8
    return
  }

  $header = @(
    "# Engram local env (PowerShell)",
    "# Usage (from repo root): . .\.env.ps1",
    "# You can append your own vars at the bottom (won't be overwritten).",
    ""
  )
  $footer = @(
    "",
    "# --- custom (user) ---",
    '# $env:SOME_KEY = ''value'''
  )
  $content = ($header + $autoBlock + $footer) -join "`r`n"
  Set-Content -LiteralPath $path -Value ($content.TrimEnd() + "`r`n") -Encoding UTF8
}

# Resolve repo root
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
if ([string]::IsNullOrWhiteSpace($EnvPath)) {
  $EnvPath = Join-Path $repoRoot ".env.ps1"
} elseif (-not [System.IO.Path]::IsPathRooted($EnvPath)) {
  $EnvPath = Join-Path $repoRoot $EnvPath
}

# Ensure and load config
_EnsureConfig $ConfigPath
. $ConfigPath

# Best-effort variable lookup (config.ps1 may use $Global: or no scope)
function _TryGetVarValue([string]$name) {
  $v = Get-Variable -Name $name -ErrorAction SilentlyContinue
  if ($null -ne $v) { return $v.Value }
  $v = Get-Variable -Name $name -Scope Global -ErrorAction SilentlyContinue
  if ($null -ne $v) { return $v.Value }
  return $null
}

# Defaults from config (best-effort; fall back if not set)
$pgHostVal = _TryGetVarValue "PgHost"
$pgPortVal = _TryGetVarValue "PgPort"
$pgDbVal = _TryGetVarValue "PgDb"
$pgSuperUserVal = _TryGetVarValue "PgSuperUser"
$engramPortVal = _TryGetVarValue "EngramPort"
$openMemoryPortVal = _TryGetVarValue "OpenMemoryPort"
$engramEnvVal = _TryGetVarValue "EngramEnv"
$openMemoryEnvVal = _TryGetVarValue "OpenMemoryEnv"

$pgHost = if ($null -ne $pgHostVal -and -not [string]::IsNullOrWhiteSpace([string]$pgHostVal)) { [string]$pgHostVal } else { "127.0.0.1" }
$pgPort = if ($null -ne $pgPortVal -and -not [string]::IsNullOrWhiteSpace([string]$pgPortVal)) { [string]$pgPortVal } else { "5432" }
$pgDb   = if ($null -ne $pgDbVal -and -not [string]::IsNullOrWhiteSpace([string]$pgDbVal)) { [string]$pgDbVal } else { "engram" }
$pgSuperUser = if ($null -ne $pgSuperUserVal -and -not [string]::IsNullOrWhiteSpace([string]$pgSuperUserVal)) { [string]$pgSuperUserVal } else { "postgres" }

$gatewayPort = "8787"
if ($null -ne $engramPortVal -and -not [string]::IsNullOrWhiteSpace([string]$engramPortVal)) { $gatewayPort = [string]$engramPortVal }
elseif (($engramEnvVal -is [System.Collections.IDictionary]) -and $engramEnvVal.Contains("GATEWAY_PORT")) { $gatewayPort = [string]$engramEnvVal["GATEWAY_PORT"] }

$omPort = "8080"
if ($null -ne $openMemoryPortVal -and -not [string]::IsNullOrWhiteSpace([string]$openMemoryPortVal)) { $omPort = [string]$openMemoryPortVal }
elseif (($openMemoryEnvVal -is [System.Collections.IDictionary]) -and $openMemoryEnvVal.Contains("OM_PORT")) { $omPort = [string]$openMemoryEnvVal["OM_PORT"] }

$projectKey = "default"
if (($engramEnvVal -is [System.Collections.IDictionary]) -and $engramEnvVal.Contains("PROJECT_KEY")) { $projectKey = [string]$engramEnvVal["PROJECT_KEY"] }

$omSchema = "openmemory"
if (($openMemoryEnvVal -is [System.Collections.IDictionary]) -and $openMemoryEnvVal.Contains("OM_PG_SCHEMA")) { $omSchema = [string]$openMemoryEnvVal["OM_PG_SCHEMA"] }

$omTier = "hybrid"
if (-not [string]::IsNullOrWhiteSpace($env:OM_TIER)) {
  $omTier = [string]$env:OM_TIER
} elseif (($openMemoryEnvVal -is [System.Collections.IDictionary]) -and $openMemoryEnvVal.Contains("OM_TIER")) {
  $omTier = [string]$openMemoryEnvVal["OM_TIER"]
}

# Detect current password env state
$pwNames = @(
  "LOGBOOK_MIGRATOR_PASSWORD",
  "LOGBOOK_SVC_PASSWORD",
  "OPENMEMORY_MIGRATOR_PASSWORD",
  "OPENMEMORY_SVC_PASSWORD"
)
$setPw = @($pwNames | Where-Object { -not [string]::IsNullOrWhiteSpace((Get-Item -Path "Env:$($_)" -ErrorAction SilentlyContinue).Value) })
$setCount = $setPw.Count

Write-Host "========== Engram Windows setup-db =========="
Write-Host ""

$mode = "logbook-only"
if ($setCount -eq 0) {
  Write-Host "No service account passwords detected."
  Write-Host "Select deployment mode:"
  Write-Host "  1) logbook-only   (no service accounts; use postgres superuser)"
  Write-Host "  2) unified-stack  (create service accounts; requires 4 passwords)"
  $c = _ReadChoice "Enter 1 or 2 [1]" "1"
  if ($c -eq "2") { $mode = "unified-stack" }
} elseif ($setCount -eq 4) {
  Write-Host "Detected 4/4 service account passwords (unified-stack)."
  Write-Host "Choose:"
  Write-Host "  1) Keep existing values (recommended)"
  Write-Host "  2) Re-enter and overwrite all 4 passwords"
  Write-Host "  3) Switch to logbook-only (clear all 4 passwords)"
  $c = _ReadChoice "Enter 1/2/3 [1]" "1"
  if ($c -eq "2") { $mode = "unified-stack" }
  elseif ($c -eq "3") { $mode = "logbook-only" }
  else { $mode = "unified-stack" }
} else {
  Write-Host ("Detected {0}/4 passwords (partial)." -f $setCount)
  Write-Host "Choose:"
  Write-Host "  1) Fill missing passwords (keep existing values)"
  Write-Host "  2) Re-enter and overwrite all 4 passwords"
  Write-Host "  3) Switch to logbook-only (clear all 4 passwords)"
  $c = _ReadChoice "Enter 1/2/3 [1]" "1"
  if ($c -eq "3") { $mode = "logbook-only" }
  else { $mode = "unified-stack" }
}

function _SetEnv([string]$name, [string]$value) {
  Set-Item -Path "Env:$name" -Value $value
}

if ($mode -eq "logbook-only") {
  foreach ($n in $pwNames) { _SetEnv $n "" }
  Write-Host ""
  Write-Host "[INFO] logbook-only: cleared 4 password env vars"
} else {
  Write-Host ""
  Write-Host "[INFO] unified-stack: enter 4 passwords (input hidden)"
  foreach ($n in $pwNames) {
    $existing = (Get-Item -Path "Env:$n" -ErrorAction SilentlyContinue).Value
    if (-not [string]::IsNullOrWhiteSpace($existing)) {
      # If already set, allow Enter to keep the current value.
      $raw = _ReadSecretPlain "$n (Enter to keep current)"
      if (-not [string]::IsNullOrWhiteSpace($raw)) { _SetEnv $n $raw }
      continue
    }
    $raw = _ReadSecretPlain $n
    if ([string]::IsNullOrWhiteSpace($raw)) { throw "unified-stack requires non-empty $n" }
    _SetEnv $n $raw
  }
}

# Optional: OM_API_KEY (recommended)
Write-Host ""
if ([string]::IsNullOrWhiteSpace($env:OM_API_KEY)) {
  Write-Host "Optional: OM_API_KEY is not set (used by OpenMemory/Gateway auth). Press Enter to skip."
  $maybe = Read-Host -Prompt "OM_API_KEY"
  if (-not [string]::IsNullOrWhiteSpace($maybe)) { _SetEnv "OM_API_KEY" $maybe.Trim() }
} else {
  Write-Host "OM_API_KEY is already set. Press Enter to keep it, or enter a new value to overwrite."
  $maybe = Read-Host -Prompt "OM_API_KEY"
  if (-not [string]::IsNullOrWhiteSpace($maybe)) { _SetEnv "OM_API_KEY" $maybe.Trim() }
}

# Ask whether to write .env.ps1
Write-Host ""
$write = _ReadChoice "Write/update $EnvPath so you can later dot-source . .\.env.ps1 ? Enter y to confirm [Y]" "Y"
if ($write -eq "y" -or $write -eq "Y") {
  $omUser = if ($mode -eq "unified-stack") { "openmemory_svc" } else { $pgSuperUser }
  $omPw = if (-not [string]::IsNullOrWhiteSpace($env:OM_PG_PASSWORD)) {
    $env:OM_PG_PASSWORD
  } elseif ($mode -eq "unified-stack" -and -not [string]::IsNullOrWhiteSpace($env:OPENMEMORY_SVC_PASSWORD)) {
    $env:OPENMEMORY_SVC_PASSWORD
  } else {
    ""
  }

  # Build POSTGRES_DSN (best-effort)
  $postgresDsn = ""
  if ($mode -eq "unified-stack" -and -not [string]::IsNullOrWhiteSpace($env:LOGBOOK_SVC_PASSWORD)) {
    $pwEnc = [System.Uri]::EscapeDataString($env:LOGBOOK_SVC_PASSWORD)
    $postgresDsn = "postgresql://logbook_svc:$pwEnc@$pgHost`:$pgPort/$pgDb"
  } elseif ($mode -eq "logbook-only") {
    # In logbook-only mode: keep user-provided POSTGRES_DSN if present; otherwise don't generate
    # (avoid writing superuser password to disk by default).
    if (-not [string]::IsNullOrWhiteSpace($env:POSTGRES_DSN)) { $postgresDsn = $env:POSTGRES_DSN }
  }

  $openmemoryBaseUrl = if (-not [string]::IsNullOrWhiteSpace($env:OPENMEMORY_BASE_URL)) {
    $env:OPENMEMORY_BASE_URL
  } else {
    "http://127.0.0.1:$omPort"
  }

  $lines = @()
  $lines += ""
  $lines += "# --- Postgres client defaults (psql/createdb) ---"
  $lines += '$env:PGUSER = ' + (_QuotePsSingle $pgSuperUser)
  $lines += '$env:PGHOST = ' + (_QuotePsSingle $pgHost)
  $lines += '$env:PGPORT = ' + (_QuotePsSingle $pgPort)
  $lines += '$env:PGDATABASE = ' + (_QuotePsSingle $pgDb)
  $lines += ""
  $lines += "# --- Engram service account passwords ---"
  foreach ($n in $pwNames) {
    $v = (Get-Item -Path "Env:$n" -ErrorAction SilentlyContinue).Value
    $lines += ('$env:' + $n + ' = ' + (_QuotePsSingle ([string]$v)))
  }
  $lines += ""
  $lines += "# --- Gateway ---"
  $lines += '$env:PROJECT_KEY = ' + (_QuotePsSingle $projectKey)
  $lines += '$env:GATEWAY_PORT = ' + (_QuotePsSingle $gatewayPort)
  $lines += '$env:OPENMEMORY_BASE_URL = ' + (_QuotePsSingle $openmemoryBaseUrl)
  if (-not [string]::IsNullOrWhiteSpace($env:OM_API_KEY)) {
    $lines += '$env:OM_API_KEY = ' + (_QuotePsSingle $env:OM_API_KEY)
  } else {
    $lines += '# $env:OM_API_KEY = ''change_me'''
  }
  if (-not [string]::IsNullOrWhiteSpace($postgresDsn)) {
    $lines += '$env:POSTGRES_DSN = ' + (_QuotePsSingle $postgresDsn)
  } else {
    $lines += '# $env:POSTGRES_DSN = ''postgresql://logbook_svc:<pwd>@127.0.0.1:5432/engram'''
  }
  $lines += ""
  $lines += "# --- OpenMemory (Node backend) ---"
  $lines += '$env:OM_METADATA_BACKEND = ' + (_QuotePsSingle "postgres")
  $lines += '$env:OM_PG_HOST = ' + (_QuotePsSingle $pgHost)
  $lines += '$env:OM_PG_PORT = ' + (_QuotePsSingle $pgPort)
  $lines += '$env:OM_PG_DB = ' + (_QuotePsSingle $pgDb)
  $lines += '$env:OM_PG_USER = ' + (_QuotePsSingle $omUser)
  if (-not [string]::IsNullOrWhiteSpace($omPw)) {
    $lines += '$env:OM_PG_PASSWORD = ' + (_QuotePsSingle $omPw)
  } else {
    $lines += '# $env:OM_PG_PASSWORD = ''change_me'''
  }
  $lines += '$env:OM_PG_SCHEMA = ' + (_QuotePsSingle $omSchema)
  $lines += '$env:OM_PORT = ' + (_QuotePsSingle $omPort)
  $lines += '$env:OM_TIER = ' + (_QuotePsSingle $omTier)

  _UpsertEnvFile $EnvPath $lines
  Write-Host "[OK] Updated env file: $EnvPath"
} else {
  Write-Host "[INFO] Skip writing env file"
}

Write-Host ""
Write-Host "[RUN] Initializing database via install_db.ps1 ..."
& (Join-Path $PSScriptRoot "install_db.ps1") -ConfigPath $ConfigPath
Write-Host "[OK] setup-db completed"

