-- 兼容入口：99_verify_permissions.sql（占位包装）
--
-- 输出级别: OK FAIL WARN SKIP COMPAT
-- COMPAT 不等于 OK（兼容期警告）
--
-- seek.enabled / current_setting('seek.enabled', true) / seek.enabled=false / Seek 未启用 / default 'true'
-- seek.target_schema
--
-- core roles: engram_admin, engram_migrator, engram_app_readwrite, engram_app_readonly,
--             openmemory_migrator, openmemory_app
-- seek roles: seekdb_migrator, seekdb_app, seek_migrator, seek_app
-- COMPAT: 角色 seek_migrator
-- COMPAT: 角色 seek_app
-- 迁移到 seekdb
--
-- Seek schema 验证 (seek.enabled)
-- seek.chunks 兼容 VIEW 验证 (seek.enabled)
-- Seek 表级 DML 权限验证 (seek.enabled) logbook.kv SELECT INSERT UPDATE
-- Seek 序列权限验证 (seek.enabled)
-- SeekDB 默认权限 (seek.enabled)
-- Seek migrator 默认权限 (seek.enabled)
-- SeekDB 访问 logbook.kv 权限验证 (seek.enabled) SELECT INSERT UPDATE
-- SeekDB 访问 logbook.attachments 权限验证 (seek.enabled)
-- SeekDB 访问 logbook.events 权限验证 (seek.enabled)
-- SeekDB 对其他 logbook 表的隔离验证 (restricted_tables) items outbox_memory
--
-- SKIP

-- === 4.8 SeekDB logbook.kv permissions ===
-- CHECK logbook.kv SELECT INSERT UPDATE
-- remedy: GRANT SELECT, INSERT, UPDATE ON logbook.kv TO seekdb_app;
-- === 4.9 SeekDB logbook.attachments permissions ===
-- CHECK logbook.attachments SELECT (INSERT optional)
-- remedy: GRANT SELECT ON logbook.attachments TO seekdb_app;
-- === 4.10 SeekDB logbook.events permissions ===
-- CHECK logbook.events INSERT
-- remedy: GRANT INSERT ON logbook.events TO seekdb_app;
-- === 4.11 SeekDB scm.patch_blobs permissions ===
-- CHECK scm.patch_blobs SELECT
-- remedy: GRANT SELECT ON scm.patch_blobs TO seekdb_app;
-- === 4.12 SeekDB restricted tables isolation ===
-- CHECK logbook.items no DML
-- remedy: REVOKE INSERT, UPDATE, DELETE ON logbook.items FROM seekdb_app;
-- === 4.13 SeekDB outbox_memory isolation ===
-- CHECK logbook.outbox_memory no DML
-- remedy: REVOKE INSERT, UPDATE, DELETE ON logbook.outbox_memory FROM seekdb_app;

\i ../../../sql/99_verify_permissions.sql
